# ===============================
# = SERVER
# ===============================

server:
  version: ${version}
  port: 9000


# ===============================
# = TIME MANAGMENT
# ===============================


time:
    token:
      unit: HOURS
      value: 1

    passwordKey:
      unit: HOURS
      value: 12



# JPA
# Connection url for the database "netgloo_blog"
#spring.datasource.url = jdbc:mysql://localhost:3306/netgloo_blog?useSSL=false

# Username and password
#spring.datasource.username = root
#spring.datasource.password = root

# Keep the connection alive if idle for a long time (needed in production)
#spring.datasource.testWhileIdle = true
#spring.datasource.validationQuery = SELECT 1

# Show or not log for each sql query
#spring.jpa.show-sql: true


# OTHER

spring:
  pid:
    fail-on-write-error1: false
    file1: /home/antosha4e/dev/projects/boot-app.pid
